# Generated by Django 2.2.16 on 2021-05-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0034_auto_20210522_0231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.RemoveField(
            model_name='community',
            name='department',
        ),
        migrations.AddField(
            model_name='community',
            name='departments',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='departments'),
        ),
    ]
