# Generated by Django 2.2.16 on 2021-05-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0035_auto_20210525_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='departments',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='departments'),
        ),
    ]
