# Generated by Django 2.2.16 on 2022-04-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0040_auto_20211216_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='title',
            field=models.CharField(max_length=64, verbose_name='title'),
        ),
    ]
