before_install:
- openssl aes-256-cbc -K $encrypted_2a03bfc35e23_key -iv $encrypted_2a03bfc35e23_iv
  -in dokku-deploy.key.enc -out .travis/dokku-deploy.key -d
- chmod +x .travis/deploy.sh

after_success:
- |
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    bash .travis/deploy.sh;
  fi;
