from .settings import *

HYDROGEN_APPS = [
    'hydrogen.apps.HydrogenAppConfig',
]

INSTALLED_APPS += HYDROGEN_APPS

GROUP_WEBSITE_MAX_LENGTH = 200
GROUP_POPULATION_MAX_LENGTH = 64
GROUP_AREA_MAX_LENGTH = 100
GROUP_ENERGY_DEMAND_MAX_LENGTH = 40
GROUP_INDUSTRY_MAX_LENGTH = 64
GROUP_EMPLOYEE_MAX_LENGTH = 32
GROUP_LOCATION_MAX_LENGTH = 64
GROUP_INSTITUTION_MAX_LENGTH = 100
GROUP_DEPARTMENT_MAX_LENGTH = 2000
GROUP_PROJECT_DURATION = 64

# firebase credential path
FIREBASE_CREDENTIALS_PATH = os.environ.get(
    'FIREBASE_CREDENTIALS_PATH',
    os.path.join(BASE_DIR, 'local/h2-firebase-adminsdk.json')
)
